backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  repo: elmarj/aliceheuff.com

media_folder: "src/static/img"
public_folder: "/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Schilderijen"
    name: "painting"
    folder: "src/paintings"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Beschrijving", name: "description", widget: "string" }
      - { label: "Schilderij", name: "image", widget: "image"}
      - widget: select
        label: "Tags"
        name: "tags"
        multiple: true
        create: true
        options: ["jazz", "fifties", "portrait", "partytime"]
  - label: "Voorpagina"
    name: "frontpage"
    files:
      - label: "Voorpagina-instellingen"
        name: "frontpage-settings"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Carousel-plaatjes
            name: carousel
            widget: object
            fields:
              - { label: Plaatje 1, name: image1, widget: image}
              - { label: Plaatje 2, name: image2, widget: image}
              - { label: Plaatje 3, name: image3, widget: image}
          - label: Linkjes
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
              - { label: Plaatje, name: img, widget: image}
      - label: "Voorpagina-inhoud"
        name: "frontpage-content"
        file: "src/index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: body, widget: markdown }
  - label: "Instellingen"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Site-Navigatie"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Menu-items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Algemene Instellingen"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
